version: "3.9"

services:
  # Laravel PHP-FPM
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - pgsql
      - redis

  # React (dev server)
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Pour watcher les fichiers sous Docker
    networks:
      - app-network

  # PostgreSQL
  pgsql:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
